[0m12:51:49.510216 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AE7E3D0A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AE7E3D0710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AE7E3D3F50>]}


============================== 12:51:49.516218 | 24ff3cb7-703f-420c-bbee-3d8c1dee259c ==============================
[0m12:51:49.516218 [info ] [MainThread]: Running with dbt=1.8.3
[0m12:51:49.517219 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\felip\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:52:04.151182 [debug] [MainThread]: Starter project path: C:\Users\felip\Envs\Felipe\e2e-dw\.venv\Lib\site-packages\dbt\include\starter_project
[0m12:52:04.177976 [info ] [MainThread]: 
Your new dbt project "e2e_datawarehouse" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:52:04.178977 [info ] [MainThread]: Setting up your profile.
[0m12:52:50.647596 [info ] [MainThread]: Profile e2e_datawarehouse written to C:\Users\felip\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:52:50.650136 [debug] [MainThread]: Command `dbt init` succeeded at 12:52:50.650136 after 61.26 seconds
[0m12:52:50.651111 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AE6A445E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AE6A898090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AE7E37F510>]}
[0m12:52:50.651111 [debug] [MainThread]: Flushing usage events
[0m12:54:09.504607 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024713ED52D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024713ED4C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024713ED6790>]}


============================== 12:54:09.509176 | 5570a589-1a5b-4bd7-9173-d45fd00606b2 ==============================
[0m12:54:09.509176 [info ] [MainThread]: Running with dbt=1.8.3
[0m12:54:09.510119 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '.', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --profiles-dir .', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:54:09.511119 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\felip\Envs\Felipe\e2e-dw\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:54:09.513126 [debug] [MainThread]: Command `dbt run` failed at 12:54:09.513126 after 0.12 seconds
[0m12:54:09.514124 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024713EF3990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002477FF45FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024713EBAB50>]}
[0m12:54:09.515125 [debug] [MainThread]: Flushing usage events
[0m12:54:49.211019 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B8C985BD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B8C9D48D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B8C9F0F90>]}


============================== 12:54:49.217027 | bd5070b8-fb90-46c2-b0e5-2b44b5e691ac ==============================
[0m12:54:49.217027 [info ] [MainThread]: Running with dbt=1.8.3
[0m12:54:49.219029 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:/Users/felip/.dbt/profiles.yml', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run --profiles-dir C:/Users/felip/.dbt/profiles.yml', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:54:49.219582 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\felip\Envs\Felipe\e2e-dw\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:54:49.222633 [debug] [MainThread]: Command `dbt run` failed at 12:54:49.221592 after 0.12 seconds
[0m12:54:49.222633 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B8C9BEC10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024BF8A45FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B8C86C190>]}
[0m12:54:49.223634 [debug] [MainThread]: Flushing usage events
